### ISSUE TITLE
META was not found

### ISSUE THREAD

**Issue by goldengun111** [riolubruh/YABDP4Nitro#42] opened 2022-11-27 17:26 UTC
With or without 0PluginLibrary.plugin.js this error keeps popping up, probably easy to fix I just don't know how to.
Latest version of discord and better discord as of 27/11/2022

![Screenshot 2022-11-27 172519](https://user-images.githubusercontent.com/96141163/204150458-fb3bccf3-4309-4860-8201-74dbdf336ea7.png)

**Comment by riolubruh** [comment] 2022-11-27 21:19
META not found means that the file is corrupt or invalid. Fully delete and redownload the plugin.
Duplicate of #31. Please Google errors like this before making issues.

**Closed by riolubruh** 2022-11-27 21:19 UTC
