### ISSUE TITLE
[Bug] Profile Banner 3y3 changes avatar instead.

### ISSUE THREAD

**Issue by Maverynthia** [riolubruh/YABDP4Nitro#158] opened 2023-11-02 16:32 UTC
![image](https://github.com/riolubruh/YABDP4Nitro/assets/2293000/6bc66d4d-b98e-400e-804a-1dc7dccc6062)
This is the avatar before I put the Imgur in the Profile banner slot. Expected: Banner changes
![image](https://github.com/riolubruh/YABDP4Nitro/assets/2293000/427f0300-8855-4f54-acea-2a124cdc9080)
Avatar changes to the banner instead of the banner.

I understand this might be due to the Discord breaks.

**Comment by riolubruh** [comment] 2023-11-02 17:07
The issue is known about and will be fixed in the next release.

**Closed** 2023-11-02 20:34 UTC
Labels: bug

**Comment by Maverynthia** [comment] 2023-11-04 08:57
Thanks, appreciate it
