### ISSUE TITLE
The Discord update broke a LOT of stuff

### ISSUE THREAD

**Issue by Vortex-sky** [riolubruh/YABDP4Nitro#154] opened 2023-10-27 10:19 UTC
When trying to turn Zere's Plugin Library on:
TypeError: Cannot read properties of undefined (reading 'id')
    at https://discord.com/assets/04dd9e416edeafbde723.js:1:1683763
    at l (https://discord.com/assets/fe753e272fca732721e3.js:1:919639)
    at U (https://discord.com/assets/04dd9e416edeafbde723.js:1:1683703)
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:19)
    at iT (https://discord.com/assets/fe753e272fca732721e3.js:1:717663)
    at l (https://discord.com/assets/fe753e272fca732721e3.js:1:772873)
    at sj (https://discord.com/assets/fe753e272fca732721e3.js:1:755889)
    at https://discord.com/assets/fe753e272fca732721e3.js:1:755755
    at sR (https://discord.com/assets/fe753e272fca732721e3.js:1:755763)
    at sO (https://discord.com/assets/fe753e272fca732721e3.js:1:752848)

**Comment by riolubruh** [comment] 2023-10-27 22:20
Duplicate of #152. Please do not make issues which are the same as an existing issue.

**Closed by riolubruh** 2023-10-27 22:20 UTC
