### ISSUE TITLE
3y3 encoding copying doesn't work

### ISSUE THREAD

**Issue by Andziaa** [riolubruh/YABDP4Nitro#129] opened 2023-08-23 20:00 UTC
I try to copy the 3y3 coding, but it doesn't work.

**Comment by riolubruh** [comment] 2023-08-23 20:15
my bad, i marked the issue for this (#126) as completed. It will be fixed in the next update (very soon!)

**Comment by riolubruh** [comment] 2023-08-23 20:16
Duplicate of #126

**Closed** 2023-08-23 20:15 UTC
