### ISSUE TITLE
Nitro Banners not animating 

### ISSUE THREAD

**Issue by remy010** [riolubruh/YABDP4Nitro#157] opened 2023-11-01 13:13 UTC
Hello Admin, can you fix this issue? The issue is that when I toggle on the plugin, I can't see other people's banners moving means that they are using Discord Nitro and putting in a GIF in their banners but when I toggle it off, the GIF banners are moving perfectly fine.

Can you fix it please?

**Comment by riolubruh** [comment] 2023-11-01 22:00
Confirmed

**Comment by riolubruh** [comment] 2023-11-01 22:17
Oh this is ironic, hahaha. The issue is caused because the original function returns a png instead of a gif lol.
Will be fixed in the next release.

**Comment by riolubruh** [comment] 2023-11-01 22:46
Figured it out. For some unknown reason, the function `getUserBannerURL` wasn't receiving the 'canAnimate' argument, so it was assuming that it couldn't!
Overriding it as below fixes the issue:
![asd](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/5eca0aab-f14d-4868-a706-aeaf84ad40f2)
However, as a side effect, nitro banners will continue animating even if the window is not focused.

**Comment by remy010** [comment] 2023-11-02 15:02
so that means you can't fix it?  It's only a bug feature?

**Comment by remy010** [comment] 2023-11-02 15:03
> Figured it out. For some unknown reason, the function `getUserBannerURL` wasn't receiving the 'canAnimate' argument, so it was assuming that it couldn't! Overriding it as below fixes the issue: ![asd](https://user-images.githubusercontent.com/54255074/279819004-5eca0aab-f14d-4868-a706-aeaf84ad40f2.png) However, as a side effect, nitro banners will continue animating even if the window is not focused (which i think literally nobody would care about or even notice tbh)

so that's means you can't fix it? It's a bug feature?

**Comment by riolubruh** [comment] 2023-11-02 15:14
As I said, **the issue can be fixed**, there's just a _minor_ side effect to the fix.

**Closed** 2023-11-02 20:34 UTC
Labels: bug
