### ISSUE TITLE
The plugin aint working for my friend

### ISSUE THREAD

**Issue by TheyThinkM** [riolubruh/YABDP4Nitro#125] opened 2023-08-23 02:53 UTC
The plugin works for me fine but it doesnt for my friend he installed both the plugin and the library but still it shows and he can edit settings (most of them turn off by themselves) but it won't let him stream with higher quality

**Comment by riolubruh** [comment] 2023-08-23 03:42
Duplicate of #122

**Closed by riolubruh** 2023-08-23 03:42 UTC
Labels: invalid

**Comment by riolubruh** [comment] 2023-08-23 03:57
Should be fixed in version 4.7.0!
