### ISSUE TITLE
Can't view live streams while streaming (source 60fps)

### ISSUE THREAD

**Issue by Obegg** [riolubruh/YABDP4Nitro#218] opened 2024-06-20 20:25 UTC
Scenario:
2 users who use `YABDP4Nitro` join a voice channel in a server,
they both share their screen on `Source` and `60fps`,
they can't view each other's share while they themself share.

**Comment by riolubruh** [comment] 2024-06-23 00:42
It's caused by this constructor:
![Discord_PIecg9fmxt](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/b695be3b-d6af-4f1a-96af-50c3e043996c)

And throws this error:
![Discord_y4JqvemxyC](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/92c1432d-ab82-4968-9a61-ff0f7315a7ef)

The reason it happens is because the plugin puts the stream's width and height in the videoBudget object, which in "Source" resolution's case, is 0. The constructor explicitly checks for 0 and, logically, throws an error if it is a 0. The reason for this is because it literally cannot construct a ladder if the pixel budget is 0. This wouldn't be a problem normally because the values in videoBudget are usually set to the maximum resolution that the user is allowed to use (i think??), however since we are changing those amounts to for our stream, it starts to complain, because it also changes the values for the stream we're watching, but only if they match the other users stream's configuration...? I have no clue if that's even remotely correct, but that's what I think is happening there. The solution is for the plugin to set literally any other value to videoBudget's width and height.

**Comment by riolubruh** [comment] 2024-06-23 01:10
Fixed in 5.4.2 (1e72ef4)

**Closed by riolubruh** 2024-06-23 01:10 UTC
Labels: bug
