### ISSUE TITLE
issue with a gif animated emojis

### ISSUE THREAD

**Issue by angrybirdice** [riolubruh/YABDP4Nitro#235] opened 2024-11-16 06:38 UTC
when i use a gif emoji it doesnt work and stays nonanimated as it is supposed to be a gif

**Comment by riolubruh** [comment] 2024-11-16 07:05
Should have already been fixed in 5.5.6. Please make sure you are fully updated and if the issue persists, let me know!

**Comment by angrybirdice** [comment] 2024-11-17 03:57
Yes it is

**Comment by 3941** [comment] 2024-11-17 04:01
> them not animating is a separate, albeit mobile-related issue which will be handled in #235.
After seeing this in the other issue that was referenced, I just want to note that I'm on desktop, not mobile.

**Comment by angrybirdice** [comment] 2024-11-17 04:17
On desktop app discord it does not animate gif emoji, I was in the current
version but the patch doesn't mention gif emoji fixed

**Comment by 3941** [comment] 2024-11-17 04:20
It was mentioned for version 5.5.6 I believe. I didn't actually try it with that version, I think.

**Comment by AkiraStein** [comment] 2024-11-17 05:08
If you want a temporary crutch solution: get favorite media plugin, check the option to hide medias that are in a category in fav media settings, check the option "upload emotes as images" in YABD, then send animated emotes that you frequently use on some private server or whatever, add them to favorite gifs and create a category there so it doesn't clog your fav gifs list.
It also adds a search bar for fav gifs so that and categories is why we're using it.
Don't forget to uncheck "upload as images" after you're done, unless you're ok with all your emotes appearing huge for mobile users (then you don't need that crutch in the 1st place).

**Comment by riolubruh** [comment] 2024-11-17 05:47
cant do shit rn since the messages api is fucked so i will see what i can do tomorrow

**Comment by riolubruh** [comment] 2024-11-18 06:09
idk what Discord did or why, but for some reason if seemingly any parameter is included in the emoji URL, when it embeds, it wont render/appear as animated (uploaded file works as intended, only affects link embeds). It makes no sense to intentionally do this, so maybe it's possible they broke it unintentionally..? Mobile renders gif slightly different than desktop which is why I said the issue is mobile-related; it needs to be considered for both platforms.

**Comment by 3941** [comment] 2024-11-18 06:20
Well, I've been playing around a little. Uploading emojis instead of linking works fine, so I'll just do that.

Speaking of that, why doesn't it work for animated stickers?

**Comment by riolubruh** [comment] 2024-11-18 06:54
> Well, I've been playing around a little. Uploading emojis instead of linking works fine, so I'll just do that.
> 
> 
> 
> Speaking of that, why doesn't it work for animated stickers? It just uploads a png
> 
> 
> 
> EDIT: oh that's funny. now I wonder if that also works for stickers.
> 
> EDIT2: nah, unfortunately not xD Anyways, that should be an easy fix for the animated emotes. Well, easy for you, not me :P

Animated stickers are in APNG (Animated PNG) format, which the Discord client for some reason doesn't support playing if the user sends/links one, and are exclusively for stickers.

As always, any time the sticker bypass in YABDP4Nitro is mentioned, I have to mention that the one in YABDP4Nitro is not very good and does not support animated stickers, and if you want an animated sticker bypass, I have a fork of FreeStickers linked in the readme which is better than the one included in YABDP and should support all sticker types including animated APNG and converting them to GIF. People really be sleeping on that shit

**Comment by 3941** [comment] 2024-11-18 07:08
FreeStickers actually working fine, apparently. Cool!
It was just going through the emoji settings that made me think of stickers at all.
It's been a long, long while since I tried getting stickers to work and I think I gave up on it at the time. My bad :)

**Comment by riolubruh** [comment] 2024-11-19 05:22
OK I did a little more testing and it seems it doesn't need to end in ".gif", it just happened that that would work. I'm still not exactly sure what criteria has to be met for it to animate properly, but just adding an ampersand (`&`) to the end seems to do the trick for some reason. The change has been pushed to 5.5.8 (6ec1117), so hopefully this issue will now actually be resolved! Since it seems to be more of an issue on Discord's end, I've also reported the issue to Discord.

**Closed** 2024-11-20 05:47 UTC
Labels: bug
