### ISSUE TITLE
ZeresPluginLibrary doesn't want to load

### ISSUE THREAD

**Issue by 01maxzie** [riolubruh/YABDP4Nitro#153] opened 2023-10-25 09:54 UTC
I came across this plugin and installed it. The plugin itself loaded but the library (named ZeresPluginLibrary) doesn't load. I don't know if this is some kind of mistake I made or Discord genuinely changed something that prevented this plugin from loading.

How do I fix this?

**Comment by FragsAreUs** [comment] 2023-10-25 10:03
you will have to wait discord did a update that broke alot of plugins even better discord it self

**Comment by 01maxzie** [comment] 2023-10-25 10:04
Oh alright, I was trying to use this plugin.

**Comment by riolubruh** [comment] 2023-10-25 17:18
Duplicate of #152

**Closed by riolubruh** 2023-10-25 17:19 UTC
